"""Inventory/reuse missing Grade 2 mock audio; fill three attested phrase IPAs.

New speech, when required, is generated by complete_mock_audio.ps1 from the
returned exact-surface inventory. Never overwrite existing MP3s or nonempty IPA.
"""
import argparse
import json
import shutil
from pathlib import Path
from check_eiken1_alignment import ROOT, load, item_surface, expected_audio_path, audio_slug

IPA={'having spent':'/ˈhævɪŋ spɛnt/','has spent':'/hæz spɛnt/','had spent':'/hæd spɛnt/'}

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply',action='store_true')
    parser.add_argument('--output',default='out/mock-audio-ipa-20261008/inventory.json')
    args=parser.parse_args()
    manifest=load(ROOT/'data/manifest.json')['q1']
    donors={}
    for ds,meta in manifest.items():
        vocab=load(ROOT/meta['vocabUrl'])
        for item in vocab.get('words',[])+vocab.get('idioms',[]):
            path=expected_audio_path(ds,item)
            if path.is_file() and path.stat().st_size:
                donors.setdefault(item_surface(item).casefold(),path)
    jobs=[];ipa_changes=[]
    asset_donors={}
    for audio in sorted((ROOT/'assets/audio').rglob('*.mp3')):
        if audio.stat().st_size:asset_donors.setdefault(audio.stem,audio)
    for ds in [f'eiken2-mock-{n}' for n in range(1,5)]:
        path=ROOT/manifest[ds]['vocabUrl'];vocab=load(path);changed=False
        for item in vocab['words']+vocab['idioms']:
            surface=item_surface(item);target=expected_audio_path(ds,item)
            if not target.is_file() or not target.stat().st_size:
                donor=donors.get(surface.casefold()) or asset_donors.get(audio_slug(surface))
                jobs.append({'dataset':ds,'q':item['q'],'surface':surface,'target':target.relative_to(ROOT).as_posix(),'source':donor.relative_to(ROOT).as_posix() if donor else None,'method':'exact-surface-copy' if donor else 'local-en-US-TTS'})
                if args.apply and donor:
                    target.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(donor,target)
            if surface in IPA and not item.get('ipa'):
                ipa_changes.append({'dataset':ds,'q':item['q'],'surface':surface,'ipa':IPA[surface]})
                item['ipa']=IPA[surface];changed=True
        if args.apply and changed:path.write_bytes((json.dumps(vocab,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
    result={'audio':jobs,'ipa':ipa_changes,'ipaPolicy':'Broad en-US strong/citation forms; compositional phrase transcriptions, not dictionary phrase quotes.',
        'sources':['https://dictionary.cambridge.org/dictionary/english/have','https://dictionary.cambridge.org/us/dictionary/english/spent','https://www.merriam-webster.com/dictionary/have']}
    output=ROOT/args.output;output.parent.mkdir(parents=True,exist_ok=True)
    output.write_bytes((json.dumps(result,ensure_ascii=False,indent=2)+'\n').encode('utf-8'))
    print(f'Audio {len(jobs)}: reuse {sum(bool(x["source"]) for x in jobs)}, new {sum(not x["source"] for x in jobs)}. IPA {len(ipa_changes)}.')
    for x in jobs:
        if not x['source']:print('New speech:',x['surface'])

if __name__=='__main__':main()
