"""国際医療福祉大学セットの語源注記。

出題文から抽出した学習語彙に対して、暗記カードで使える短い説明を
付ける。複数語の表現と、語源表示対象外として記録された語は対象にしない。
"""

from __future__ import annotations


# 見出し語 -> 語源・語形成の短い説明
ETYMOLOGY = {
    "creation": "ラテン語 creare（生み出す）に由来。新しく生み出されたもの。",
    "definition": "ラテン語 definire（境界を定める）に由来。物事の境界をはっきりさせること。",
    "expenditure": "ラテン語 expendere（重さを量って支払う）に由来。外へ支払う費用。",
    "immigration": "ラテン語 immigrare（中へ移り住む）に由来。in-（中へ）＋migrare（移る）。",
    "uniform": "ラテン語 unus（一つ）＋ forma（形）。形が一つにそろった状態。",
    "mutual": "ラテン語 mutuus（相互の、交換された）に由来。互いに行き来する関係。",
    "apparent": "ラテン語 apparere（現れる、目に見える）に由来。目に見えて明らかな。",
    "various": "ラテン語 varius（さまざまな、変化する）に由来。異なるものがある状態。",
    "factor": "ラテン語 facere（する、作る）から派生した factor（作るもの）。結果を生む要因。",
    "ratio": "ラテン語 ratio（計算、割合、理由）に由来。計算した割合。",
    "passage": "ラテン語 passus（一歩、通過）に由来。通り過ぎることから、通路・一節。",
    "resources": "ラテン語 surgere（立ち上がる）をもとにした resource。再び湧き上がるもの。",
    "preferential": "ラテン語 praeferre（前へ運ぶ、より好む）に由来。先に選ばれる、優遇される。",
    "local": "ラテン語 locus（場所）に由来。特定の場所に関する。",
    "male": "ラテン語 masculus（男性の）に由来。",
    "medical": "ラテン語 medicus（医療の）に由来。mederi（治す）と関係する。",
    "reveal": "ラテン語 revelare（覆いを取り去る）に由来。隠れたものを明らかにする。",
    "support": "ラテン語 supportare（下から運ぶ）に由来。下から支える。",
    "increase": "ラテン語 increscere（成長する、増える）に由来。大きくなること。",
    "reduce": "ラテン語 reducere（後ろへ導く、戻す）に由来。量や負担を小さくする。",
    "students": "ラテン語 studere（熱心に取り組む、学ぶ）に由来する student＋複数形 -s。",
    "professionals": "ラテン語 profiteri（公に宣言する）に由来する profession＋-al＋複数形 -s。",
    "doctors": "ラテン語 docere（教える）に由来する doctor＋複数形 -s。",
    "issue": "ラテン語 exire（外へ出る）に由来。外へ出たもの・公に出されたものから「発行する」。",
    "promote": "ラテン語 promovere（前へ動かす）に由来。人を上位へ進める、物事を促進する。",
    "advanced": "advance（前へ進める）＋-ed。先へ進んだ状態から「高度な」。",
    "skilled": "skill（技量）＋-ed。skill は古ノルド語 skil（区別、知識）に由来。",
    "average": "フランス語 avarie（船荷の損害）を経て、損失を公平に分担する意味から「平均」へ。語源の細部には諸説ある。",
    "course": "ラテン語 cursus（走ること、進路）に由来。進む道から「課程」。",
    "important": "ラテン語 importare（中へ運び込む）に由来。中へ運ぶ価値がある→重要な。",
    "total": "ラテン語 totus（全部の、全体の）に由来。全体を合わせたもの。",
    "percentage": "ラテン語 per centum（100につき）に由来。100を基準にした割合。",
    "income": "in（中へ）＋come（来る）。中へ入ってくるお金→所得。",
    "individuals": "ラテン語 individuus（分けられない）に由来する individual＋複数形 -s。",
    "visas": "ラテン語 visa（見られたもの）に由来する visa＋複数形 -s。",
    "per": "ラテン語 per（〜を通って、〜につき）に由来。",
    "system": "ギリシャ語 systēma（組み立てられたもの）に由来。syn-（ともに）＋histanai（立てる）と関係する。",
    "risks": "フランス語 risque／イタリア語 risico を経て英語になった語。危険を冒すこと。語源の細部には諸説ある。",
    "security": "ラテン語 securitas（心配から解放された状態）に由来。se（〜から離れて）＋cura（心配）。",
    "positions": "ラテン語 ponere（置く）に由来する position＋複数形 -s。置かれた場所・地位。",
    "ties": "tie（結ぶ、つなぐ）＋複数形 -s。結びつきから「つながり」。",
    "function": "ラテン語 fungi（果たす、実行する）に由来。果たす働き→機能。",
    "strengthen": "strong（強い）＋-en（〜にする）。強くする。",
    "number": "ラテン語 numerus（数、量）に由来。",
    "figure": "ラテン語 figura（形、姿）に由来。形を描いたもの→図。",
    "treatment": "ラテン語 tractare（扱う、取り扱う）に由来。扱い方・処置。",
    "disparities": "ラテン語 dispar（等しくない）に由来する disparity＋複数形 -ies。",
    "growth": "grow（成長する）＋-th。成長した結果や過程。",
    "fiscal": "ラテン語 fiscus（国庫、金庫）に由来。国庫に関することから財政の。",
    "doctoral": "doctor（教える人、学識者）＋-al。doctor はラテン語 docere（教える）に由来。",
    "international": "inter-（〜の間）＋nation（国）＋-al。国と国の間の。",
    "female": "ラテン語 femella（若い女性）に由来。femina（女性）の指小形。",
    "table": "ラテン語 tabula（板、書板）に由来。板に書いたもの→表。",
    "expenses": "ラテン語 expendere（量って支払う）に由来する expense＋複数形 -s。",
    "economic": "ギリシャ語 oikonomikos（家の管理に関する）に由来。oikos（家）＋nomos（管理・規則）。",
    "quickly": "quick（生きている、活発な）＋-ly。素早く。",
    "benefits": "ラテン語 bene（よく）＋facere（する）に由来する benefit＋複数形 -s。よいこと・利益。",
    "proportion": "ラテン語 proportio（釣り合い、割合）に由来。pro-（前へ）＋portio（部分）。",
}


# 新規 origin エントリに付ける Etymonline の見出し。キーは原形化後のキー。
ORIGIN_SOURCE_SLUGS = {
    "creation": "creation",
    "uniform": "uniform",
    "mutual": "mutual",
    "apparent": "apparent",
    "various": "various",
    "ratio": "ratio",
    "passage": "passage",
    "local": "local",
    "male": "male",
    "medical": "medical",
    "reveal": "reveal",
    "students": "student",
    "professionals": "professional",
    "doctors": "doctor",
    "issue": "issue",
    "promote": "promote",
    "advanced": "advance",
    "skilled": "skill",
    "average": "average",
    "course": "course",
    "total": "total",
    "percentage": "percentage",
    "income": "income",
    "immigration": "immigration",
    "individual": "individual",
    "per": "per",
    "system": "system",
    "risks": "risk",
    "security": "security",
    "economic": "economic",
    "ties": "tie",
    "function": "function",
    "strengthen": "strengthen",
    "number": "number",
    "figure": "figure",
    "treatment": "treatment",
    "growth": "growth",
    "fiscal": "fiscal",
    "doctoral": "doctor",
    "female": "female",
    "table": "table",
    "quickly": "quick",
    "benefits": "benefit",
}
