"""1級模試の熟語核心イメージ。生成元へ取り込むための共有データ。"""

from __future__ import annotations


CORE_IMAGES_BY_ROUND = {'mock-2': {'crept up on': {'chain': [{'term': 'creep', 'gloss': '忍び寄る'},
                                      {'term': 'up', 'gloss': '近づいて上がる'},
                                      {'term': 'on', 'gloss': '対象に向かって'},
                                      {'gloss': '相手に少しずつ近づく'},
                                      {'gloss': '徐々に近づいた、不意に襲った'}],
                            'particle': 'up',
                            'particleSense': 'approach'},
            'chipped away at': {'chain': [{'term': 'chip', 'gloss': '少しずつ削る'},
                                          {'term': 'away', 'gloss': '離れていく'},
                                          {'gloss': '少しずつ外へ削り続ける'},
                                          {'gloss': '少しずつ削った、地道に取り組んだ'}],
                                'particle': 'away'},
            'cashed in on': {'chain': [{'term': 'cash', 'gloss': '現金にする'},
                                       {'term': 'in', 'gloss': '中へ取り込む'},
                                       {'term': 'on', 'gloss': '対象に乗せる'},
                                       {'gloss': '機会を取り込んで利益に変える'},
                                       {'gloss': '〜を利用して利益を得た'}],
                             'particle': 'in'},
            'put in for': {'chain': [{'term': 'put', 'gloss': '置く'},
                                     {'term': 'in', 'gloss': '中へ入れる'},
                                     {'term': 'for', 'gloss': '目的に向けて'},
                                     {'gloss': '申請を中へ差し出す'},
                                     {'gloss': '〜を申請した、応募した'}],
                           'particle': 'in'},
            'brimmed over': {'chain': [{'term': 'brim', 'gloss': '縁まで満たす'},
                                       {'term': 'over', 'gloss': '境目を越えて'},
                                       {'gloss': '縁を越えてあふれる'},
                                       {'gloss': 'あふれた、満ちあふれた'}],
                             'particle': 'over'},
            'copped out': {'chain': [{'term': 'cop', 'gloss': 'つかむ・引き受ける'},
                                     {'term': 'out', 'gloss': '外へ逃れる'},
                                     {'gloss': '責任の外へ逃げる'},
                                     {'gloss': '逃げた、責任を回避した'}],
                           'particle': 'out',
                           'particleSense': 'escape'},
            'leveled off': {'chain': [{'term': 'level', 'gloss': '平らにする'},
                                      {'term': 'off', 'gloss': '離れて弱まる'},
                                      {'gloss': '上昇の勢いが離れて平らになる'},
                                      {'gloss': '横ばいになった、安定した'}],
                            'particle': 'off',
                            'particleSense': 'weaken'},
            'played off': {'chain': [{'term': 'play', 'gloss': '動かす・演じる'},
                                     {'term': 'off', 'gloss': '離れた側へ'},
                                     {'gloss': '二つの側を離れた位置で動かす'},
                                     {'gloss': '対立させた、うまく利用した'}],
                           'particle': 'off',
                           'particleSense': 'separate'},
            'bogging down': {'chain': [{'term': 'bog', 'gloss': '沼にはめる'},
                                       {'term': 'down', 'gloss': '下へ押さえつける'},
                                       {'gloss': '動きを下へ沈めて止める'},
                                       {'gloss': '動きを遅くする、停滞させる'}],
                             'particle': 'down',
                             'particleSense': 'reduce'},
            'phasing out': {'chain': [{'term': 'phase', 'gloss': '段階を進める'},
                                      {'term': 'out', 'gloss': '外へ取り除く'},
                                      {'gloss': '段階を踏んで外へ出す'},
                                      {'gloss': '段階的に廃止する'}],
                            'particle': 'out',
                            'particleSense': 'remove'},
            'staking out': {'chain': [{'term': 'stake', 'gloss': '杭を打つ'},
                                      {'term': 'out', 'gloss': '外へ線を引く'},
                                      {'gloss': '杭で場所を外側から区切る'},
                                      {'gloss': '見張る、場所を確保する'}],
                            'particle': 'out',
                            'particleSense': 'reserve'},
            'hemming in': {'chain': [{'term': 'hem', 'gloss': '縁を囲う'},
                                     {'term': 'in', 'gloss': '内側へ閉じ込める'},
                                     {'gloss': '縁で内側を囲んで動けなくする'},
                                     {'gloss': '取り囲む、行動を制限する'}],
                           'particle': 'in'},
            'taper off': {'chain': [{'term': 'taper', 'gloss': '先細りにする'},
                                    {'term': 'off', 'gloss': '離れて弱まる'},
                                    {'gloss': '先細りになり、勢いが離れる'},
                                    {'gloss': '次第に弱まる、減少する'}],
                          'particle': 'off',
                          'particleSense': 'weaken'},
            'work out': {'chain': [{'term': 'work', 'gloss': '働かせる'},
                                   {'term': 'out', 'gloss': '外へほどく'},
                                   {'gloss': '働かせて問題を外へほどく'},
                                   {'gloss': '解決する、うまくいく'}],
                         'particle': 'out',
                         'particleSense': 'resolve'},
            'fan out': {'chain': [{'term': 'fan', 'gloss': '扇状に広げる'},
                                  {'term': 'out', 'gloss': '外へ広がる'},
                                  {'gloss': '中心から外へ扇状に広げる'},
                                  {'gloss': '扇状に広がる、散開する'}],
                        'particle': 'out',
                        'particleSense': 'spread'},
            'blare out': {'chain': [{'term': 'blare', 'gloss': '大音量で鳴らす'},
                                    {'term': 'out', 'gloss': '外へ音を出す'},
                                    {'gloss': '音を外へ強く響かせる'},
                                    {'gloss': '大音量で鳴り響く'}],
                          'particle': 'out',
                          'particleSense': 'express'}},
 'mock-3': {'dabble in': {'chain': [{'term': 'dabble', 'gloss': '水を軽くかき回す'},
                                    {'term': 'in', 'gloss': '中へ入り込む'},
                                    {'gloss': '一部だけ中へ手を入れて試す'},
                                    {'gloss': '〜にちょっと手を出す'}],
                          'particle': 'in'},
            'let down': {'chain': [{'term': 'let', 'gloss': '許す・させる'},
                                   {'term': 'down', 'gloss': '下へ落とす'},
                                   {'gloss': '期待や支えを下へ落とす'},
                                   {'gloss': '失望させる'}],
                         'particle': 'down',
                         'particleSense': 'lower'},
            'put across': {'chain': [{'term': 'put', 'gloss': '置く'},
                                     {'term': 'across', 'gloss': '向こう側へ渡す'},
                                     {'gloss': '考えを相手側へ渡して置く'},
                                     {'gloss': 'うまく伝える、売り込む'}],
                           'particle': 'across'},
            'farm out': {'chain': [{'term': 'farm', 'gloss': '農場で育てる'},
                                   {'term': 'out', 'gloss': '外へ任せる'},
                                   {'gloss': '仕事を外へ出して任せる'},
                                   {'gloss': '外注する'}],
                         'particle': 'out',
                         'particleSense': 'delegate'},
            'stumbled upon': {'chain': [{'term': 'stumble', 'gloss': 'つまずく'},
                                        {'term': 'upon', 'gloss': 'その上・その場で'},
                                        {'gloss': 'つまずいた先で出会う'},
                                        {'gloss': '偶然見つける'}],
                              'particle': 'upon'},
            'chipped off': {'chain': [{'term': 'chip', 'gloss': '少しずつ削る'},
                                      {'term': 'off', 'gloss': '切り離して'},
                                      {'gloss': '表面から小片を切り離す'},
                                      {'gloss': '少しずつ削り取った、剥がした'}],
                            'particle': 'off',
                            'particleSense': 'separate'},
            'marked out': {'chain': [{'term': 'mark', 'gloss': '印を付ける'},
                                     {'term': 'out', 'gloss': '外へ線を引く'},
                                     {'gloss': '印で外側から区切って示す'},
                                     {'gloss': '選び出した、目立たせた'}],
                           'particle': 'out',
                           'particleSense': 'reserve'},
            'fawned over': {'chain': [{'term': 'fawn', 'gloss': '子鹿のようにすり寄る'},
                                      {'term': 'over', 'gloss': '上から覆うように'},
                                      {'gloss': '相手の上に甘く寄りかかる'},
                                      {'gloss': 'へつらった、ちやほやした'}],
                            'particle': 'over'},
            'laid on': {'chain': [{'term': 'lay', 'gloss': '置く・載せる'},
                                  {'term': 'on', 'gloss': '接触させて上に'},
                                  {'gloss': '上に載せて加える'},
                                  {'gloss': '加えた、施した'}],
                        'particle': 'on',
                        'particleSense': 'contact'},
            'keyed up': {'chain': [{'term': 'key', 'gloss': '鍵をかける・調整する'},
                                   {'term': 'up', 'gloss': '上へ状態を動かす'},
                                   {'gloss': '気持ちを上へ持ち上げて高める'},
                                   {'gloss': '興奮して、高揚して'}],
                         'particle': 'up',
                         'particleSense': 'raise'},
            'banked on': {'chain': [{'term': 'bank', 'gloss': '銀行に預ける'},
                                    {'term': 'on', 'gloss': '対象に乗せる'},
                                    {'gloss': '見込みを対象に預ける'},
                                    {'gloss': '〜を当てにした'}],
                          'particle': 'on',
                          'particleSense': 'rely'},
            'held down': {'chain': [{'term': 'hold', 'gloss': '保持する'},
                                    {'term': 'down', 'gloss': '下へ押さえる'},
                                    {'gloss': '下へ押さえたまま保つ'},
                                    {'gloss': '抑えた、押さえつけた'}],
                          'particle': 'down',
                          'particleSense': 'suppress'},
            'backed out': {'chain': [{'term': 'back', 'gloss': '後ろへ下がる'},
                                     {'term': 'out', 'gloss': '外へ引く'},
                                     {'gloss': '後ろへ引いて外へ出る'},
                                     {'gloss': '手を引いた、約束を撤回した'}],
                           'particle': 'out',
                           'particleSense': 'escape'},
            'flipped out': {'chain': [{'term': 'flip', 'gloss': 'ひっくり返す'},
                                      {'term': 'out', 'gloss': '外へ噴き出す'},
                                      {'gloss': '感情を外へひっくり返す'},
                                      {'gloss': 'ひどく取り乱した、激怒した'}],
                            'particle': 'out',
                            'particleSense': 'express'},
            'squeaked by': {'particle': 'by',
                            'chain': [{'term': 'squeak', 'gloss': 'かろうじて通る'},
                                      {'term': 'by', 'gloss': 'ぎりぎりそばを通り抜けて'},
                                      {'gloss': 'そばをすり抜けて通過する'}]},
            'sank in': {'chain': [{'term': 'sink', 'gloss': '沈む'},
                                  {'term': 'in', 'gloss': '内側へ入る'},
                                  {'gloss': '意味が内側へ沈み込む'},
                                  {'gloss': '理解される、実感される'}],
                        'particle': 'in'}},
 'mock-4': {'roped into': {'chain': [{'term': 'rope', 'gloss': 'ロープで引く'},
                                     {'term': 'into', 'gloss': '中へ引き込む'},
                                     {'gloss': 'ロープで中へ引き入れる'},
                                     {'gloss': '無理に引き込まれた'}],
                           'particle': 'into'},
            'factored in': {'chain': [{'term': 'factor', 'gloss': '要素として数える'},
                                      {'term': 'in', 'gloss': '中へ含める'},
                                      {'gloss': '計算の中へ要素を入れる'},
                                      {'gloss': '考慮に入れた'}],
                            'particle': 'in'},
            'frowned on': {'chain': [{'term': 'frown', 'gloss': '眉をひそめる'},
                                     {'term': 'on', 'gloss': '対象に向ける'},
                                     {'gloss': '対象に眉をひそめて向ける'},
                                     {'gloss': '快く思わなかった、認めなかった'}],
                           'particle': 'on',
                           'particleSense': 'contact'},
            'smoothed down': {'chain': [{'term': 'smooth', 'gloss': 'なめらかにする'},
                                        {'term': 'down', 'gloss': '下へ落ち着かせる'},
                                        {'gloss': '表面や対立を下へ平らにする'},
                                        {'gloss': 'なだめた、平らにした'}],
                              'particle': 'down',
                              'particleSense': 'reduce'},
            'fire up': {'chain': [{'term': 'fire', 'gloss': '火をつける'},
                                  {'term': 'up', 'gloss': '上へ勢いを高める'},
                                  {'gloss': '火をつけて気持ちを上げる'},
                                  {'gloss': '奮起させる、活気づける'}],
                        'particle': 'up',
                        'particleSense': 'raise'},
            'root out': {'chain': [{'term': 'root', 'gloss': '根を張る'},
                                   {'term': 'out', 'gloss': '外へ取り除く'},
                                   {'gloss': '根ごと外へ引き抜く'},
                                   {'gloss': '根絶する、見つけ出す'}],
                         'particle': 'out',
                         'particleSense': 'remove'},
            'lap up': {'chain': [{'term': 'lap', 'gloss': '舌ですくう'},
                                 {'term': 'up', 'gloss': '上へ取り込む'},
                                 {'gloss': 'すくい上げるように喜んで取り込む'},
                                 {'gloss': '喜んで受け入れる、がつがつ食べる'}],
                       'particle': 'up',
                       'particleSense': 'complete'},
            'pass down': {'chain': [{'term': 'pass', 'gloss': '渡す'},
                                    {'term': 'down', 'gloss': '下の世代へ'},
                                    {'gloss': '下へ順に渡していく'},
                                    {'gloss': '受け継がせる、伝える'}],
                          'particle': 'down',
                          'particleSense': 'descend'},
            'threw out': {'chain': [{'term': 'throw', 'gloss': '投げる'},
                                    {'term': 'out', 'gloss': '外へ放り出す'},
                                    {'gloss': '外へ投げ出す'},
                                    {'gloss': '痛めた、捨てた'}],
                          'particle': 'out',
                          'particleSense': 'remove'},
            'scraped together': {'chain': [{'term': 'scrape', 'gloss': 'こすり集める'},
                                           {'term': 'together', 'gloss': '一つに集める'},
                                           {'gloss': '少しずつこすって一つに寄せる'},
                                           {'gloss': 'かき集めた'}],
                                 'particle': 'together'},
            'pushed up': {'chain': [{'term': 'push', 'gloss': '押す'},
                                    {'term': 'up', 'gloss': '上へ押し上げる'},
                                    {'gloss': '下から上へ押し上げる'},
                                    {'gloss': '押し上げた'}],
                          'particle': 'up',
                          'particleSense': 'raise'},
            'forced back': {'chain': [{'term': 'force', 'gloss': '力をかける'},
                                      {'term': 'back', 'gloss': '後ろへ戻す'},
                                      {'gloss': '力で後ろへ押し戻す'},
                                      {'gloss': '押し戻した'}],
                            'particle': 'back'},
            'heading up': {'chain': [{'term': 'head', 'gloss': '頭を向ける'},
                                     {'term': 'up', 'gloss': '上へ向ける'},
                                     {'gloss': '先頭へ向かって進める'},
                                     {'gloss': '率いる'}],
                           'particle': 'up',
                           'particleSense': 'raise'},
            'piecing together': {'chain': [{'term': 'piece', 'gloss': '小片にする'},
                                           {'term': 'together', 'gloss': '一つに組み合わせる'},
                                           {'gloss': '小片をつなぎ合わせる'},
                                           {'gloss': 'つなぎ合わせて理解する'}],
                                 'particle': 'together'},
            'punching out': {'chain': [{'term': 'punch', 'gloss': '殴る'},
                                       {'term': 'out', 'gloss': '外へ倒す'},
                                       {'gloss': '外へ殴り出して倒す'},
                                       {'gloss': '殴り倒す、退勤打刻する'}],
                             'particle': 'out',
                             'particleSense': 'remove'},
            'stirring up': {'chain': [{'term': 'stir', 'gloss': 'かき混ぜる'},
                                      {'term': 'up', 'gloss': '上へ勢いを高める'},
                                      {'gloss': '中のものをかき混ぜて表へ動かす'},
                                      {'gloss': '引き起こす、かき立てる'}],
                            'particle': 'up',
                                   'particleSense': 'raise'}}}
