"""英検1級の自作模試で共有する語源説明の正本。"""

from __future__ import annotations


ETYMOLOGY_BY_ROUND = {
    "mock-2": {
        "dispatched": "ラテン語 disponere（配分する）を経た dispatch（急いで送り出す）＋-ed。",
        "trampled": "trample（踏みつける）＋-ed。trampleの詳しい語源は不確か。",
        "touted": "tout（盛んに売り込む）＋-ed。toutの詳しい語源は不確か。",
        "toppled": "top（頂部）から派生した topple（倒れる、倒す）＋-ed。",
        "bluntly": "blunt（鈍い、率直な）＋-ly。bluntは古フランス語系の語。",
        "innately": "ラテン語 innatus（生まれつきの）に由来する innate＋-ly。",
        "astutely": "ラテン語 astutus（抜け目のない）に由来する astute＋-ly。",
        "devoutly": "ラテン語 devovere（身をささげる）に由来する devout＋-ly。",
        "streaking": "streak（線、一筋に走る）＋-ing。streakは古英語系の語。",
        "canvassing": "canvas（帆布）から、戸別に歩いて意見を集める意味へ発達した canvass＋-ing。",
        "impelling": "ラテン語 impellere（押して動かす）に由来する impel＋-ing。",
        "honing": "古英語 han（砥石）に由来する hone＋-ing。",
        "rigorous": "ラテン語 rigor（硬さ、厳しさ）に由来。",
        "perplexed": "ラテン語 perplexus（絡み合った）に由来する perplex＋-ed。",
        "insurgent": "ラテン語 insurgere（立ち上がる）に由来。in-（上へ）＋surgere（立つ）。",
        "sedate": "ラテン語 sedare（静める）に由来。sedere（座る）と関係する。",
        "palliative": "ラテン語 palliare（覆って和らげる）に由来。pallium（覆い）と関係する。",
        "sinister": "ラテン語 sinister（左の）に由来。古代の不吉な左という観念から意味が広がった。",
        "colloquial": "ラテン語 colloqui（ともに話す）に由来。col-（ともに）＋loqui（話す）。",
        "destitute": "ラテン語 destituere（置き去りにする）に由来。de-（離して）＋statuere（立てる）。",
        "arcane": "ラテン語 arcanus（秘密の、隠された）に由来。",
        "inclement": "ラテン語 inclemens（慈悲のない、厳しい）に由来。",
        "benevolent": "ラテン語 bene（よく）＋volens（望む）に由来。",
        "covetous": "古フランス語 coveitous（欲深い）に由来。詳しい語形成は不確か。",
        "dissuade": "ラテン語 dissuadere（思いとどまらせる）に由来。dis-（離して）＋suadere（勧める）。",
        "straddle": "古英語 strædlan（またぐ）に由来。",
        "contravene": "ラテン語 contra（反対に）＋venire（来る）に由来。",
        "infiltrate": "ラテン語 in-（中へ）＋filtrum（ろ過布）に由来する infiltrate。",
        "perforation": "ラテン語 perforare（穴を通す）に由来。per-（通して）＋forare（穴を開ける）。",
        "culmination": "ラテン語 culmen（頂、頂点）に由来。",
        "adulation": "ラテン語 adulatio（へつらい）に由来。adulari（お世辞を言う）と関係する。",
        "abomination": "ラテン語 abominatio（忌み嫌うこと）に由来。ab-（離れて）＋omen（前兆）。",
        "ranted": "rant（わめく、激しく言う）＋-ed。rantの詳しい語源は不確か。",
        "strutted": "strut（気取って歩く）＋-ed。strutの詳しい語源は不確か。",
        "poached": "poach（密猟する、湯煮する）＋-ed。poachは古フランス語系の語。",
        "shuffled": "shuffle（足を引きずる、混ぜる）＋-ed。shuffleの詳しい語源は不確か。",
        "constellation": "ラテン語 constellatio（星の集まり）に由来。con-（ともに）＋stella（星）。",
        "paucity": "ラテン語 paucus（少ない）に由来。",
        "deadlock": "dead（動かない）＋lock（錠、固定）からなる英語の複合語。",
        "headway": "head（先頭）＋way（道）から、前進や進展の意味になった複合語。",
        "insinuate": "ラテン語 insinuare（胸中へ入り込ませる）に由来。sinus（湾、懐）と関係する。",
        "decant": "フランス語 décanterを経て、ラテン語 decanthare（容器から注ぐ）に由来。",
        "deprecate": "ラテン語 deprecari（祈って避ける、非難する）に由来。",
        "dislodge": "古フランス語 deslogier（宿から追い出す）に由来。",
        "layover": "lay（置く）＋over（越えて）からなる英語の複合語。途中で横たわって待つこと。",
        "vigil": "ラテン語 vigil（目を覚ましている）に由来。",
        "convalescence": "ラテン語 convalescere（力を取り戻す）に由来。con-（ともに）＋valere（強い）。",
        "stint": "古英語 styntan（止める、制限する）に由来。",
        "vigilant": "ラテン語 vigilare（目を覚まして見張る）に由来。",
        "consensual": "ラテン語 consentire（ともに感じる、同意する）に由来。",
        "turbulent": "ラテン語 turbulentus（乱れた）に由来。turba（騒ぎ、群衆）と関係する。",
        "terse": "ラテン語 tersus（きれいに拭かれた、簡潔な）に由来。",
        "attrition": "ラテン語 atterere（こすり減らす）に由来。ad-（〜へ）＋terere（こする）。",
        "apparition": "ラテン語 apparere（現れる）に由来。ad-（〜へ）＋parere（現れる）。",
        "revelation": "ラテン語 revelare（覆いを取り去る）に由来。re-（再び）＋velum（覆い）。",
        "ratification": "ラテン語 ratificare（有効だと確認する）に由来。ratus（確定した）＋facere（する）。",
        "expropriated": "ラテン語 expropriare（所有物を取り上げる）に由来。ex-（外へ）＋proprius（自分の）。",
        "modulated": "ラテン語 modulatus（尺度に合わせた）に由来する modulate＋-ed。",
        "piqued": "フランス語 piquer（刺す）に由来する pique＋-ed。好奇心を刺激する意へ。",
        "enumerated": "ラテン語 enumerare（数え上げる）に由来。e-（外へ）＋numerus（数）。",
        "divulgence": "ラテン語 divulgare（広く知らせる）に由来。vulgus（民衆）と関係する。",
        "blasphemy": "ギリシャ語 blasphēmia（悪口、冒涜）に由来。",
        "plagiarism": "ラテン語 plagiarus（誘拐犯、盗用者）に由来。",
        "walkout": "walk（歩く）＋out（外へ）からなる英語の複合語。",
        "acceded": "ラテン語 accedere（近づく、同意する）に由来する accede＋-ed。",
        "stammered": "stammer（どもる）＋-ed。stammerの詳しい語源は不確か。",
        "whined": "古英語 hwinsian（泣き声を出す）に由来する whine＋-ed。",
        "resonated": "ラテン語 resonare（反響する）に由来する resonate＋-ed。re-（返って）＋sonare（響く）。",
        "unwieldy": "un-（〜でない）＋wield（扱う）＋-y。扱いにくい性質を表す。",
        "ailing": "ail（苦しむ、病む）＋-ing。ailは古フランス語系の語。",
        "excruciating": "ラテン語 excruciare（十字架にかけて苦しめる）に由来。ex-（外へ）＋crux（十字架）。",
        "infallible": "ラテン語 in-（否定）＋fallibilis（誤りうる）に由来。fallere（だます、誤らせる）と関係する。",
        "pageant": "古フランス語 pageant（舞台、見世物）に由来。",
        "spasm": "ギリシャ語 spasmos（引きつり、けいれん）に由来。",
        "morass": "フランス語 marais（沼地）と関係する語。詳しい語形成は不確か。",
        "litany": "ギリシャ語 litaneia（祈願）に由来。",
        "pretexts": "ラテン語 praetextus（前に織ったもの、口実）に由来する pretext＋複数形 -s。",
        "ledgers": "ledger（置かれた記録帳）＋複数形 -s。ledgerの詳しい語源は不確か。",
        "requisites": "ラテン語 requirere（強く求める）に由来する requisite＋複数形 -s。",
        "facades": "フランス語 façade（顔、建物の正面）に由来する facade＋複数形 -s。",
        "foist": "foist（押しつける）に由来。詳しい語源は不確か。",
        "muffle": "古フランス語 moufle（手袋、覆い）に由来。",
        "enunciate": "ラテン語 enuntiare（はっきり述べる）に由来。e-（外へ）＋nuntiare（告げる）。",
        "ascribe": "ラテン語 ascribere（書き加える、帰する）に由来。ad-（〜へ）＋scribere（書く）。",
        "crept up on": "creep（忍び寄る）＋up（近づいて）＋on（〜に）からなる句動詞。",
        "chipped away at": "chip（小片を削る）＋away（少しずつ離して）＋at（〜に）からなる句動詞。",
        "cashed in on": "cash（現金化する）＋in（中へ）＋on（〜を利用して）からなる句動詞。",
        "put in for": "put（置く）＋in（中へ）＋for（〜を求めて）からなる句動詞。",
        "brimmed over": "brim（縁まで満たす）＋over（越えて）からなる句動詞。",
        "copped out": "cop out（責任から逃げる）からなる口語的な句動詞。copの詳しい語源は不確か。",
        "leveled off": "level（平らにする）＋off（差をなくして）からなる句動詞。",
        "played off": "play（働きかける）＋off（互いに離して）からなる句動詞。",
        "bogging down": "bog（沼にはまらせる）＋down（下へ）からなる句動詞。bogの詳しい語源は不確か。",
        "phasing out": "phase（段階）＋out（外へ）からなる句動詞。段階的に終わらせること。",
        "staking out": "stake（杭）＋out（外へ置いて）からなる句動詞。境界を杭で示すこと。",
        "hemming in": "hem（縁取りする）＋in（内側へ）からなる句動詞。周囲を囲むこと。",
        "taper off": "taper（先細りにする）＋off（離れて）からなる句動詞。",
        "work out": "work（働く）＋out（外へ、最後まで）からなる句動詞。",
        "fan out": "fan（扇）＋out（外へ）からなる句動詞。扇状に広がること。",
        "blare out": "blare（大音量で鳴る）＋out（外へ）からなる句動詞。blareの詳しい語源は不確か。",
    },
    "mock-3": {
        "degenerating": "ラテン語 degenerare（種から外れる、悪化する）に由来する degenerate＋-ing。",
        "haggling": "haggle（値段を細かく交渉する）＋-ing。haggleの詳しい語源は不確か。",
        "scowling": "scowl（しかめ面をする）＋-ing。scowlの詳しい語源は不確か。",
        "bluffing": "bluff（虚勢を張る、はったりをかける）＋-ing。詳しい語源は不確か。",
        "devious": "ラテン語 devius（道から外れた）に由来。de-（離れて）＋via（道）。",
        "magnanimous": "ラテン語 magnus（大きい）＋animus（心、精神）に由来。",
        "deciduous": "ラテン語 decidere（落ちる）に由来。de-（下へ）＋cadere（落ちる）。",
        "oblivious": "ラテン語 oblivisci（忘れる）に由来。",
        "regimes": "フランス語 régimeを経たラテン語 regimen（統治、指導）に由来する regime＋複数形 -s。",
        "glimmers": "glimmer（かすかな光）＋複数形 -s。詳しい語源は不確か。",
        "liaisons": "フランス語 liaison（結合、連絡）に由来。lier（結ぶ）と関係する。",
        "glitches": "glitch（小さな不具合）＋複数形 -es。詳しい語源は不確か。",
        "debarred": "de-（離して）＋bar（棒、妨げる）に由来する debar＋-ed。",
        "spearheaded": "spearhead（槍の穂先、先頭に立つ）＋-edからなる複合語。",
        "beckoned": "beckon（手招きする）＋-ed。beckonの詳しい語源は不確か。",
        "reciprocated": "ラテン語 reciprocus（行き来する）に由来する reciprocate＋-ed。",
        "pivot": "フランス語 pivot（回転軸）に由来。",
        "onset": "on（上に、始めて）＋set（置く）からなる英語の複合語。",
        "gradient": "ラテン語 gradi（歩む）に由来。gradus（歩み、段階）と関係する。",
        "jab": "jab（突く、突き）に由来。詳しい語源は不確か。",
        "stakes": "stake（杭、賭け金）＋複数形 -s。stakeはゲルマン系の語。",
        "sanctuaries": "ラテン語 sanctuarium（聖所）に由来する sanctuary＋複数形 -ies。",
        "shrugs": "shrug（肩をすくめる）＋複数形 -s。詳しい語源は不確か。",
        "factions": "ラテン語 facere（作る、行う）に由来する faction＋複数形 -s。",
        "somberly": "フランス語 sombre（暗い）に由来する somber＋-ly。",
        "idly": "idle（何もしない）＋-ly。idleは古英語 īdelに由来。",
        "flagrantly": "ラテン語 flagrare（燃える）に由来する flagrant＋-ly。",
        "inherently": "ラテン語 inhaerere（くっついている）に由来する inherent＋-ly。",
        "sanctified": "ラテン語 sanctus（聖なる）＋facere（する）に由来する sanctify＋-ed。",
        "convened": "ラテン語 convenire（ともに来る、集まる）に由来する convene＋-ed。",
        "detracted": "ラテン語 detrahere（引き下ろす）に由来する detract＋-ed。",
        "bequeathed": "古英語 becwethan（言い残す）に由来する bequeath＋-ed。",
        "slanting": "slant（斜めに傾く）＋-ing。slantの詳しい語源は不確か。",
        "inhaling": "ラテン語 inhalare（息を吸い込む）に由来する inhale＋-ing。",
        "deflecting": "ラテン語 deflectere（曲げてそらす）に由来する deflect＋-ing。",
        "whetting": "古英語 hwettan（鋭くする）に由来する whet＋-ing。",
        "sumptuous": "ラテン語 sumptuosus（費用のかかる、豪華な）に由来。sumere（取る、費やす）と関係する。",
        "transient": "ラテン語 transire（通り過ぎる）に由来。trans-（越えて）＋ire（行く）。",
        "mundane": "ラテン語 mundanus（世界の）に由来。mundus（世界）と関係する。",
        "pessimistic": "ラテン語 pessimus（最悪の）に由来する pessimism＋-istic。",
        "lenient": "ラテン語 lenire（和らげる）に由来。",
        "frantic": "ギリシャ語 phrenitis（脳の炎症）を経て、取り乱した状態の意へ。",
        "ascetic": "ギリシャ語 askētikos（修行の）に由来。askein（鍛錬する）と関係する。",
        "livid": "ラテン語 lividus（青黒い、鉛色の）に由来。",
        "fared": "古英語 faran（進む、旅する）に由来する fare＋-ed。",
        "compounded": "ラテン語 componere（ともに置く）に由来する compound＋-ed。",
        "succumbed": "ラテン語 succumbere（下に横たわる、屈する）に由来する succumb＋-ed。",
        "corroded": "ラテン語 corrodere（かじり尽くす）に由来する corrode＋-ed。",
        "disembarking": "フランス語 débarquer（船から降ろす）に由来する disembark＋-ing。",
        "acquiescing": "ラテン語 acquiescere（静かに休む、黙って従う）に由来する acquiesce＋-ing。",
        "delving": "古英語 delfan（掘る）に由来する delve＋-ing。",
        "infringing": "ラテン語 infringere（壊す、侵害する）に由来する infringe＋-ing。",
        "coronation": "ラテン語 corona（冠）に由来。",
        "vogue": "フランス語 vogue（流行、航行）に由来。",
        "maneuver": "フランス語 manœuvre（手仕事）に由来。main（手）＋œuvre（仕事）。",
        "protocol": "ギリシャ語 prōtokollon（最初に貼った紙）に由来。prōtos（最初）＋kolla（糊）。",
        "abort": "ラテン語 abortare（早く失う、流産する）に由来。",
        "reclaim": "ラテン語 reclamare（強く呼び戻す）に由来。re-（再び）＋clamare（叫ぶ）。",
        "pinpoint": "pin（ピン）＋point（点）からなる英語の複合語。",
        "insulate": "ラテン語 insula（島）に由来。周囲から切り離された島のイメージ。",
        "exemplary": "ラテン語 exemplum（例、見本）に由来。",
        "haggard": "haggard（やつれた）に由来。詳しい語源は不確か。",
        "insipid": "ラテン語 insipidus（味のない）に由来。in-（否定）＋sapidus（味のある）。",
        "petulant": "ラテン語 petulans（攻撃的な、気まぐれな）に由来。petere（求める、攻撃する）と関係する。",
        "envoy": "古フランス語 envoi（派遣、使者）に由来。envoyer（送る）と関係する。",
        "allegory": "ギリシャ語 allēgoria（別のことを語ること）に由来。allos（別の）＋agoreuein（話す）。",
        "gall": "gall（胆汁、厚かましさ）に由来。詳しい語源は不確か。",
        "intrigue": "ラテン語 intricare（絡ませる）に由来。in-（中へ）＋tricae（困難、もつれ）。",
        "reprisals": "フランス語 représailles（報復）に由来する reprisal＋複数形 -s。",
        "provisos": "ラテン語 proviso（前もって定めた条件）に由来する proviso＋複数形 -s。",
        "apexes": "ラテン語 apex（頂点、先端）に由来する apex＋複数形 -es。",
        "fringes": "古フランス語 fringe（縁飾り）に由来する fringe＋複数形 -s。",
        "onslaught": "on（上に、対して）＋slaught（打撃）からなる英語の複合語。",
        "archipelago": "ギリシャ語 archipelagos（主な海、群島）に由来。arkhi-（主な）＋pelagos（海）。",
        "aberration": "ラテン語 aberrare（道から外れる）に由来。ab-（離れて）＋errare（さまよう）。",
        "sham": "英語 sham（見せかけ）に由来。詳しい語源は不確か。",
        "devouring": "ラテン語 devorare（飲み込む）に由来する devour＋-ing。",
        "cradling": "古英語 cradol（ゆりかご）に由来する cradle＋-ing。",
        "pondering": "ラテン語 ponderare（重さを量る、考える）に由来する ponder＋-ing。",
        "juxtaposing": "ラテン語 juxta（そばに）＋ponere（置く）に由来する juxtapose＋-ing。",
        "negligent": "ラテン語 neglegere（軽視する、怠る）に由来。nec（〜でない）＋legere（選ぶ、気にかける）。",
        "pedantic": "ギリシャ語 paidagōgikos（教師の）に由来。pais（子ども）＋agōgos（導く人）。",
        "dainty": "古フランス語 deintie（価値、上品さ）に由来。",
        "introspective": "ラテン語 intro（内へ）＋specere（見る）に由来。",
        "dabble in": "dabble（液体を少し扱う）＋in（〜の中で）からなる句動詞。dabbleの詳しい語源は不確か。",
        "let down": "let（許す、下げる）＋down（下へ）からなる句動詞。",
        "put across": "put（置く）＋across（向こう側へ）からなる句動詞。考えを相手へ渡すこと。",
        "farm out": "farm（請け負わせる）＋out（外へ）からなる句動詞。",
        "stumbled upon": "stumble（つまずく）＋upon（〜の上へ）からなる句動詞。偶然出会うこと。",
        "chipped off": "chip（小片を削る）＋off（離して）からなる句動詞。",
        "marked out": "mark（印を付ける）＋out（外へ、明確に）からなる句動詞。",
        "fawned over": "fawn（子鹿のようにへつらう）＋over（〜に対して）からなる句動詞。",
        "laid on": "lay（置く、加える）＋on（上に）からなる句動詞。",
        "keyed up": "key（調子を合わせる）＋up（高めて）からなる句動詞。",
        "banked on": "bank（銀行に預ける）＋on（〜を頼りに）からなる句動詞。",
        "held down": "hold（保持する）＋down（下に押さえて）からなる句動詞。",
        "backed out": "back（後ろへ動かす）＋out（外へ）からなる句動詞。",
        "flipped out": "flip（ひっくり返す）＋out（外へ）からなる口語的な句動詞。",
        "squeaked by": "squeak（きしむ、小さな音を出す）＋by（そばを通って）からなる句動詞。",
        "sank in": "sink（沈む）＋in（中へ）からなる句動詞。意味が心の中へ沈むこと。",
    },
    "mock-4": {
        "implements": "ラテン語 implere（満たす、実行する）を経た implement＋三人称語尾 -s。",
        "curfews": "フランス語 couvre-feu（火を覆うもの）に由来する curfew＋複数形 -s。",
        "pitfalls": "pit（穴）＋fall（落ちる）からなる英語の複合語＋複数形 -s。",
        "grouches": "grouch（不平を言う人）＋複数形 -es。grouchの詳しい語源は不確か。",
        "allegedly": "ラテン語 allegare（申し立てる）に由来する allege＋-edly。",
        "unabashedly": "un-（否定）＋abash（当惑させる）＋-ed＋-ly。",
        "nonchalantly": "フランス語 nonchaloir（気にかけない）に由来する nonchalant＋-ly。",
        "ascetically": "ギリシャ語 askētikos（修行の）に由来する ascetic＋-ally。",
        "novice": "ラテン語 novicius（新しい、初心者の）に由来。novus（新しい）と関係する。",
        "connoisseur": "フランス語 connoisseur（知識のある人）に由来。connaître（知る）と関係する。",
        "pushover": "push（押す）＋over（向こうへ）からなる英語の複合語。",
        "bigot": "bigot（偏狭な人）に由来。詳しい語源は不確か。",
        "stampede": "スペイン語 estampida（驚いて逃げること）に由来。",
        "graft": "graft（接ぎ木、結び付け）に由来。詳しい語源は不確か。",
        "convergence": "ラテン語 convergere（ともに向かう）に由来。con-（ともに）＋vergere（向かう）。",
        "rapport": "フランス語 rapport（関係、持ち帰るもの）に由来。rapporter（運び戻す）と関係する。",
        "evocative": "ラテン語 evocare（呼び出す）に由来。e-（外へ）＋vocare（呼ぶ）。",
        "ponderous": "ラテン語 ponderosus（重い）に由来。pondus（重さ）と関係する。",
        "bogus": "英語 bogus（偽の）に由来。詳しい語源は不確か。",
        "rowdy": "rowdy（騒々しい）に由来。row（騒ぎ）から派生した語。",
        "surmising": "古フランス語 surmettre（上に置く、推測する）に由来する surmise＋-ing。",
        "dissecting": "ラテン語 dissecare（切り分ける）に由来。dis-（分けて）＋secare（切る）。",
        "swilling": "古英語 swilian（洗い流す、飲む）に由来する swill＋-ing。",
        "muddling": "muddle（混乱させる、混ぜる）＋-ing。muddleの詳しい語源は不確か。",
        "pry": "古フランス語 preier（注意深く見る、調べる）に由来。",
        "cogitate": "ラテン語 cogitare（ともに考える）に由来。co-（ともに）＋agitare（動かす）。",
        "writhe": "古英語 writhan（ねじる）に由来。",
        "consort": "ラテン語 consors（運命をともにする）に由来。con-（ともに）＋sors（運命）。",
        "complacency": "ラテン語 complacere（十分に喜ばせる）に由来。com-（完全に）＋placere（喜ばせる）。",
        "echelon": "フランス語 échelon（はしごの段）に由来。",
        "vicinity": "ラテン語 vicinitas（近さ、近隣）に由来。vicinus（近い）と関係する。",
        "rupture": "ラテン語 rumpere（破る）に由来。",
        "disdain": "古フランス語 desdeign（軽蔑）に由来。des-（否定）＋deign（価値があると考える）。",
        "expedite": "ラテン語 expedire（足かせを外す、容易にする）に由来。ex-（外へ）＋pes（足）。",
        "shackle": "古英語 scacel（足かせ）に由来。",
        "annex": "ラテン語 annectere（結び付ける）に由来。ad-（〜へ）＋nectere（結ぶ）。",
        "agnostic": "ギリシャ語 a-（〜でない）＋gnōstos（知られた）に由来。",
        "distraught": "ラテン語 distrahere（引き裂く）に由来する distraught。心が引き裂かれた状態。",
        "enamored": "古フランス語 enamourer（恋をさせる）に由来する enamor＋-ed。",
        "remedial": "ラテン語 remedium（治療、救済）に由来。re-（再び）＋mederi（治す）。",
        "tacit": "ラテン語 tacitus（黙った）に由来。tacere（黙る）と関係する。",
        "tangible": "ラテン語 tangere（触れる）に由来。",
        "rueful": "rue（後悔する）＋-ful。rueの詳しい語源は不確か。",
        "devout": "ラテン語 devovere（身をささげる）に由来。de-（完全に）＋vovere（誓う）。",
        "cordial": "ラテン語 cor（心）に由来。心からの、親しいという意味へ。",
        "impassive": "ラテン語 in-（否定）＋pati（苦しむ、感じる）に由来。",
        "elaborate": "ラテン語 elaborare（詳しく仕上げる）に由来。e-（外へ）＋laborare（働く）。",
        "flippant": "フランス語 fliper（軽く動かす）に由来。軽薄な態度の意へ。",
        "banter": "banter（冗談の言い合い）に由来。詳しい語源は不確か。",
        "jeer": "jeer（あざける声）に由来。詳しい語源は不確か。",
        "indolence": "ラテン語 indolentia（痛みを感じないこと）に由来。in-（否定）＋dolere（痛む）。",
        "boon": "古ノルド語 bón（願い、恩恵）に由来。",
        "dormant": "ラテン語 dormire（眠る）に由来。",
        "pivotal": "pivot（回転軸）＋-al。pivotはフランス語に由来。",
        "resilient": "ラテン語 resilire（跳ね返る）に由来。re-（返って）＋salire（跳ぶ）。",
        "arid": "ラテン語 aridus（乾いた）に由来。",
        "rectified": "ラテン語 rectificare（まっすぐにする）に由来する rectify＋-ed。",
        "deployed": "フランス語 déployer（広げる、配置する）に由来する deploy＋-ed。",
        "esteemed": "古フランス語 estimer（評価する）に由来する esteem＋-ed。",
        "thwarted": "thwart（横木、妨げる）＋-ed。thwartの詳しい語源は不確か。",
        "flapped": "古英語 flappian（ばたつく）に由来する flap＋-ed。",
        "nullified": "ラテン語 nullus（無の）＋facere（する）に由来する nullify＋-ed。",
        "solicited": "ラテン語 sollicitare（強く動かす、求める）に由来する solicit＋-ed。",
        "pawned": "古フランス語 pan（質、担保）に由来する pawn＋-ed。",
        "depreciating": "ラテン語 depretiari（価値を下げる）に由来する depreciate＋-ing。",
        "clobbering": "clobber（強く打つ、圧倒する）＋-ing。詳しい語源は不確か。",
        "relishing": "古フランス語 relecher（なめ直す）に由来する relish＋-ing。",
        "averting": "ラテン語 avertere（向きをそらす）に由来する avert＋-ing。",
        "sloth": "古英語 slǣwð（怠惰）に由来。",
        "tremor": "ラテン語 tremor（震え）に由来。tremere（震える）と関係する。",
        "obscurity": "ラテン語 obscurus（暗い、隠れた）に由来。",
        "brunt": "brunt（最大の打撃）に由来。詳しい語源は不確か。",
        "placebo": "ラテン語 placebo（私は喜ばせるだろう）に由来。placere（喜ばせる）と関係する。",
        "rebound": "古フランス語 rebondir（跳ね返る）に由来。re-（返って）＋bondir（跳ぶ）。",
        "salvo": "イタリア語 salvo（安全に、斉射）に由来。ラテン語 salvus（安全な）と関係する。",
        "transgression": "ラテン語 transgredi（越えて歩く）に由来。trans-（越えて）＋gradi（歩む）。",
        "vying": "vie（競う）＋-ing。vieは古フランス語 envierと関係する。",
        "proliferating": "ラテン語 proles（子孫）＋ferre（生む、運ぶ）に由来する proliferate＋-ing。",
        "soaring": "soar（高く舞い上がる）＋-ing。詳しい語源は不確か。",
        "snowballing": "snowball（雪玉、雪だるま式に増える）＋-ingからなる複合語。",
        "invigorated": "ラテン語 vigor（活力）に由来する invigorate＋-ed。",
        "dredged": "dredge（さらう、掘り起こす）＋-ed。詳しい語源は不確か。",
        "saturated": "ラテン語 saturare（満たす）に由来する saturate＋-ed。",
        "infatuated": "ラテン語 infatuare（愚かにする）に由来する infatuate＋-ed。",
        "roped into": "rope（ロープ）＋into（中へ）からなる句動詞。人を中へ引き込むこと。",
        "factored in": "factor（要因）＋in（中へ）からなる句動詞。要因として中に入れること。",
        "frowned on": "frown（しかめ面）＋on（〜に対して）からなる句動詞。",
        "smoothed down": "smooth（滑らかにする）＋down（落ち着かせて）からなる句動詞。",
        "fire up": "fire（火をつける）＋up（高めて）からなる句動詞。",
        "root out": "root（根）＋out（外へ）からなる句動詞。根から外へ抜くこと。",
        "lap up": "lap（舌でなめる）＋up（完全に）からなる句動詞。",
        "pass down": "pass（渡す）＋down（下へ、後の世代へ）からなる句動詞。",
        "threw out": "throw（投げる）＋out（外へ）からなる句動詞。",
        "scraped together": "scrape（こすり取る）＋together（ともに）からなる句動詞。",
        "pushed up": "push（押す）＋up（上へ）からなる句動詞。",
        "forced back": "force（力を加える）＋back（後ろへ）からなる句動詞。",
        "heading up": "head（先頭に立つ）＋up（上へ）からなる句動詞。",
        "piecing together": "piece（断片）＋together（ともに）からなる句動詞。",
        "punching out": "punch（こぶしで打つ）＋out（外へ）からなる句動詞。",
        "stirring up": "stir（かき混ぜる）＋up（引き起こして）からなる句動詞。",
    },
}
