"""英検1級公式過去問の熟語核心イメージ。生成元へ取り込むための共有データ。"""

from __future__ import annotations


CORE_IMAGES_BY_ROUND = {'2025-2': {'pony up': {'particle': 'up',
                        'particleSense': 'settle',
                        'chain': [{'term': 'pony', 'gloss': 'ポニー'},
                                  {'term': 'up', 'gloss': '決めて片づけて'},
                                  {'gloss': 'ポニーを買うように金を出す'},
                                  {'gloss': '支払いのために金を出す'}]},
            'buckle down': {'particle': 'down',
                            'particleSense': 'settle',
                            'chain': [{'term': 'buckle', 'gloss': '締め具を締める'},
                                      {'term': 'down', 'gloss': '腰を据えて'},
                                      {'gloss': '気持ちを引き締めて向き合う'},
                                      {'gloss': '気を引き締めて本腰を入れる'}]},
            'foul up': {'particle': 'up',
                        'particleSense': 'disrupt',
                        'chain': [{'term': 'foul', 'gloss': '汚す'},
                                  {'term': 'up', 'gloss': '状態を乱して'},
                                  {'gloss': '手順を乱してしまう'},
                                  {'gloss': '手順を乱して失敗させる'}]},
            'cast down': {'particle': 'down',
                          'particleSense': 'lower',
                          'chain': [{'term': 'cast', 'gloss': '投げる'},
                                    {'term': 'down', 'gloss': '気持ちや評価を下げて'},
                                    {'gloss': '気持ちを下へ落とす'},
                                    {'gloss': '気持ちを落とし込んで落胆させる'}]},
            'breeze in': {'particle': 'in',
                          'chain': [{'term': 'breeze', 'gloss': 'そよ風'},
                                    {'term': 'in', 'gloss': '中へ入って'},
                                    {'gloss': 'そよ風のように中へ入る'},
                                    {'gloss': 'ふらりと中へ入ってくる'}]},
            'branch off': {'particle': 'off',
                           'particleSense': 'separate',
                           'chain': [{'term': 'branch', 'gloss': '枝'},
                                     {'term': 'off', 'gloss': '本体から切り離して'},
                                     {'gloss': '枝のように本道から分かれる'},
                                     {'gloss': '本道から分かれて別方向へ進む'}]},
            'crack down': {'particle': 'down',
                           'particleSense': 'suppress',
                           'chain': [{'term': 'crack', 'gloss': 'ひびを入れる'},
                                     {'term': 'down', 'gloss': '下へ押さえつけて'},
                                     {'gloss': '力を加えて押さえ込む'},
                                     {'gloss': '厳しく押さえ込んで取り締まる'}]},
            'lop off': {'particle': 'off',
                        'particleSense': 'separate',
                        'chain': [{'term': 'lop', 'gloss': '切り落とす'},
                                  {'term': 'off', 'gloss': '本体から切り離して'},
                                  {'gloss': '余分な部分を切り離す'},
                                  {'gloss': '余分な部分を切り離して落とす'}]},
            'dwell on': {'particle': 'on',
                         'particleSense': 'contact',
                         'chain': [{'term': 'dwell', 'gloss': 'とどまる'},
                                   {'term': 'on', 'gloss': '対象に向けて接して'},
                                   {'gloss': '意識を対象にとどめる'},
                                   {'gloss': '対象に意識をとどめてくよくよ考える'}]},
            'reel off': {'particle': 'off',
                         'particleSense': 'separate',
                         'chain': [{'term': 'reel', 'gloss': 'リールから繰り出す'},
                                   {'term': 'off', 'gloss': '次々と外へ繰り出して'},
                                   {'gloss': '次々と外へ繰り出す'},
                                   {'gloss': '次々と外へ繰り出してすらすら言う'}]},
            'rustle up': {'particle': 'up',
                          'particleSense': 'prepare',
                          'chain': [{'term': 'rustle', 'gloss': '急いで動かす'},
                                    {'term': 'up', 'gloss': '整えて用意して'},
                                    {'gloss': '材料をかき集める'},
                                    {'gloss': '材料をかき集めて急いで用意する'}]},
            'haul off': {'particle': 'off',
                         'particleSense': 'separate',
                         'chain': [{'term': 'haul', 'gloss': '重い物を引く'},
                                   {'term': 'off', 'gloss': '本体から切り離して'},
                                   {'gloss': 'その場から引き離す'},
                                   {'gloss': 'その場から急に持ち去る'}]},
            'fritter away': {'particle': 'away',
                             'chain': [{'term': 'fritter', 'gloss': '少しずつ浪費する'},
                                       {'term': 'away', 'gloss': '手元から遠ざけて'},
                                       {'gloss': '手元から少しずつ遠ざける'},
                                       {'gloss': '少しずつ遠ざけて浪費する'}]},
            'rip off': {'particle': 'off',
                        'particleSense': 'separate',
                        'chain': [{'term': 'rip', 'gloss': '引き裂く'},
                                  {'term': 'off', 'gloss': '本体から切り離して'},
                                  {'gloss': '相手から引き離して取る'},
                                  {'gloss': '相手から不当に奪い取る'}]},
            'sound off': {'particle': 'off',
                          'particleSense': 'express',
                          'chain': [{'term': 'sound', 'gloss': '音を出す'},
                                    {'term': 'off', 'gloss': '外へ出して'},
                                    {'gloss': '外へ声を出して主張する'},
                                    {'gloss': '外へ声を出して意見をぶちまける'}]},
            'crop up': {'particle': 'up',
                        'particleSense': 'appear',
                        'chain': [{'term': 'crop', 'gloss': '突然現れる'},
                                  {'term': 'up', 'gloss': '上へ現れて'},
                                  {'gloss': '表面にひょいと現れる'},
                                  {'gloss': '問題などが突然現れる'}]}},
 '2025-3': {'nod off': {'particle': 'off',
                        'particleSense': 'weaken',
                        'chain': [{'term': 'nod', 'gloss': 'うなずく'},
                                  {'term': 'off', 'gloss': '意識から離れて'},
                                  {'gloss': '意識が離れて眠りに落ちる'}]},
            'pipe down': {'particle': 'down',
                          'particleSense': 'reduce',
                          'chain': [{'term': 'pipe', 'gloss': '管から音を出す'},
                                    {'term': 'down', 'gloss': '勢いや量を下げて'},
                                    {'gloss': '音量を下げて静かになる'}]},
            'drone on': {'particle': 'on',
                         'particleSense': 'continue',
                         'chain': [{'term': 'drone', 'gloss': '単調な音を出す'},
                                   {'term': 'on', 'gloss': 'そのまま続けて'},
                                   {'gloss': 'そのまま続く'}]},
            'crank out': {'particle': 'out',
                          'particleSense': 'produce',
                          'chain': [{'term': 'crank', 'gloss': 'ハンドルを回す'},
                                    {'term': 'out', 'gloss': '外へ作り出して'},
                                    {'gloss': '外へ次々と出す'}]},
            'tail off': {'particle': 'off',
                         'particleSense': 'weaken',
                         'chain': [{'term': 'tail', 'gloss': '尾を引く'},
                                   {'term': 'off', 'gloss': '離れて弱まって'},
                                   {'gloss': '勢いが離れて弱まる'}]},
            'patch up': {'particle': 'up',
                         'particleSense': 'complete',
                         'chain': [{'term': 'patch', 'gloss': 'つぎを当てて直す'},
                                   {'term': 'up', 'gloss': '整った状態まで'},
                                   {'gloss': '整った状態まで仕上げる'}]},
            'choke off': {'particle': 'off',
                          'particleSense': 'separate',
                          'chain': [{'term': 'choke', 'gloss': '息を詰まらせる'},
                                    {'term': 'off', 'gloss': '本体から切り離して'},
                                    {'gloss': '流れを切って止める'}]},
            'own up': {'particle': 'up',
                       'particleSense': 'admit',
                       'chain': [{'term': 'own', 'gloss': '自分のものだと認める'},
                                 {'term': 'up', 'gloss': '表へ出して'},
                                 {'gloss': '表に出して認める'}]},
            'hush up': {'particle': 'up',
                        'particleSense': 'contain',
                        'chain': [{'term': 'hush', 'gloss': '静かにさせる'},
                                  {'term': 'up', 'gloss': '内側へ収めて'},
                                  {'gloss': '表面に出ないように収める'}]},
            'get behind': {'particle': 'behind',
                           'chain': [{'term': 'get', 'gloss': 'なる'},
                                     {'term': 'behind', 'gloss': '後ろの位置へ移して'},
                                     {'gloss': '後ろの位置に入る'}]},
            'plug in': {'particle': 'in',
                        'chain': [{'term': 'plug', 'gloss': '栓を差し込む'},
                                  {'term': 'in', 'gloss': '中へ入って'},
                                  {'gloss': '中へ接続する'}]},
            'farm out': {'particle': 'out',
                         'particleSense': 'delegate',
                         'chain': [{'term': 'farm', 'gloss': '農場で扱う'},
                                   {'term': 'out', 'gloss': '外へ任せて'},
                                   {'gloss': '外へ委ねる'}]},
            'sit by': {'particle': 'by',
                       'chain': [{'term': 'sit', 'gloss': '座る'},
                                 {'term': 'by', 'gloss': 'そばに留まって'},
                                 {'gloss': 'そばに留まって何もしない'}]},
            'dive in': {'particle': 'in',
                        'chain': [{'term': 'dive', 'gloss': '飛び込む'},
                                  {'term': 'in', 'gloss': '中へ入って'},
                                  {'gloss': '中へ入り込む'}]},
            'strike back': {'particle': 'back',
                            'chain': [{'term': 'strike', 'gloss': '打つ'},
                                      {'term': 'back', 'gloss': '元の側へ戻して'},
                                      {'gloss': '相手の側へ打ち返す'}]},
            'pan out': {'particle': 'out',
                        'particleSense': 'resolve',
                        'chain': [{'term': 'pan', 'gloss': '選別用の皿で洗う'},
                                  {'term': 'out', 'gloss': '外へほどいて'},
                                  {'gloss': '結果として外に現れる'}]}},
 '2026-1': {'identify with': {'chain': [{'term': 'identify', 'gloss': '同一だと見なす'},
                                        {'term': 'with', 'gloss': '〜とともに'},
                                        {'gloss': '相手と自分を重ねる'}]},
            'reel in': {'particle': 'in',
                        'chain': [{'term': 'reel', 'gloss': 'リールを巻く'},
                                  {'term': 'in', 'gloss': '中へ入って'},
                                  {'gloss': '内側へ引き寄せる'}]},
            'polish off': {'particle': 'off',
                           'particleSense': 'separate',
                           'chain': [{'term': 'polish', 'gloss': '磨いて仕上げる'},
                                     {'term': 'off', 'gloss': '残りを切り離して'},
                                     {'gloss': '残りを離して片付ける'}]},
            'black out': {'particle': 'out',
                          'particleSense': 'remove',
                          'chain': [{'term': 'black', 'gloss': '黒く塗りつぶす'},
                                    {'term': 'out', 'gloss': '外へ取り除いて'},
                                    {'gloss': '外から見えない状態にする'}]},
            'turn up': {'particle': 'up',
                        'particleSense': 'appear',
                        'chain': [{'term': 'turn', 'gloss': '向きを変える'},
                                  {'term': 'up', 'gloss': '上へ現れて'},
                                  {'gloss': '上向きに現れる・高める'}]},
            'grow on': {'particle': 'on',
                        'particleSense': 'contact',
                        'chain': [{'term': 'grow', 'gloss': '成長する'},
                                  {'term': 'on', 'gloss': '対象に向けて接して'},
                                  {'gloss': '対象に接する影響が積み重なる'}]},
            'build in': {'particle': 'in',
                         'chain': [{'term': 'build', 'gloss': '組み立てる'},
                                   {'term': 'in', 'gloss': '中へ入って'},
                                   {'gloss': '中に組み込む'}]},
            'churn out': {'particle': 'out',
                          'particleSense': 'produce',
                          'chain': [{'term': 'churn', 'gloss': 'かき混ぜて作る'},
                                    {'term': 'out', 'gloss': '外へ作り出して'},
                                    {'gloss': '外へ大量に作り出す'}]},
            'tamper with': {'chain': [{'term': 'tamper', 'gloss': '勝手にいじる'},
                                      {'term': 'with', 'gloss': '対象に対して'},
                                      {'gloss': '対象を不適切に変更する'}]},
            'ease off': {'particle': 'off',
                         'particleSense': 'weaken',
                         'chain': [{'term': 'ease', 'gloss': '和らぐ'},
                                   {'term': 'off', 'gloss': '離れて弱まって'},
                                   {'gloss': '勢いが離れて弱まる'}]},
            'trump up': {'particle': 'up',
                         'particleSense': 'fabricate',
                         'chain': [{'term': 'trump', 'gloss': '切り札を出す'},
                                   {'term': 'up', 'gloss': '表へ作り上げて'},
                                   {'gloss': '表に持ち上げて作り上げる'}]},
            'branch out': {'particle': 'out',
                           'particleSense': 'spread',
                           'chain': [{'term': 'branch', 'gloss': '枝分かれする'},
                                     {'term': 'out', 'gloss': '外へ広げて'},
                                     {'gloss': '外へ広がって新しい領域へ進む'}]},
            'dole out': {'particle': 'out',
                         'particleSense': 'delegate',
                         'chain': [{'term': 'dole', 'gloss': '分け前を与える'},
                                   {'term': 'out', 'gloss': '外へ任せて'},
                                   {'gloss': '外へ少しずつ配る'}]},
            'clam up': {'particle': 'up',
                        'particleSense': 'contain',
                        'chain': [{'term': 'clam', 'gloss': '二枚貝を閉じる'},
                                  {'term': 'up', 'gloss': '口を閉じて'},
                                  {'gloss': '口を閉じて黙る'}]},
            'mete out': {'particle': 'out',
                         'particleSense': 'delegate',
                         'chain': [{'term': 'mete', 'gloss': '割り当てる'},
                                   {'term': 'out', 'gloss': '外へ任せて'},
                                   {'gloss': '外へ与える'}]},
            'pluck up': {'particle': 'up',
                         'particleSense': 'raise',
                         'chain': [{'term': 'pluck', 'gloss': '引き抜く'},
                                   {'term': 'up', 'gloss': '上へ持ち上げて'},
                                   {'gloss': '気持ちを持ち上げて奮い起こす'}]}}}
